### ISSUE TITLE
Addon not working since last update of HA. Could you please fix this?

### ISSUE THREAD

**Issue by rucanunes** [ljmerza/ha-our-groceries#31] opened 2022-12-12 12:35 UTC
## Configuration

```yaml

Add your logs here.

```

## Describe the bug

Not working since last update of HA

## Debug log

```text

Unable to install package ourgroceries==1.5.0: ERROR: Cannot install ourgroceries==1.5.0 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts [notice] A new release of pip available: 22.3 -> 22.3.1 [notice] To update, run: pip install --upgrade pip

```

**Comment by Mucka911** [comment] 2022-12-12 17:18
Hello getting same issue as well.

**Comment by chicknlil** [comment] 2022-12-13 02:14
Same.

`Logger: homeassistant.setup
Source: setup.py:202
First occurred: 7:08:50 PM (1 occurrences)
Last logged: 7:08:50 PM

Setup failed for custom integration ourgroceries: Requirements for ourgroceries not found: ['ourgroceries==1.5.0'].`

**Comment by DataBitz** [comment] 2022-12-13 09:39
Was broken initially after 2022.12.0 and beta but then was fixed after ha-our-groceries 1.5.0.
Seems to be broken again since 2022.12.2 or 2022.12.3.

**Comment by bschatzow** [comment] 2022-12-13 16:15
Still broken on 12.4 release.

**Comment by frenck** [comment] 2022-12-13 16:59
The issue is caused by the pins here:

https://github.com/ljmerza/py-our-groceries/blob/32d6600fa602cd452dfd56a6836fe926f6646fa1/setup.py#L6-L7

```
    'aiohttp==3.8.3',
    'beautifulsoup4==4.11.1'
```

Packages/libraries should not pin strictly but instead, pin a minimal version or ping a range with a minimal and max version for subdependencies.

For example, is there a specific reason that library only works with `aiohttp` 3.8.3 and not with 3.8.1? Or why wouldn't it work with 3.7.x?

../Frenck

**Comment by rucanunes** [comment] 2022-12-13 20:27
Is there a way to fix this issue?

**Comment by malaki86** [comment] 2022-12-13 20:29
Just found out about Ourgroceries & the HA integration today. I was ripping out what's left of my hair trying to get it working in HA.

**Comment by frenck** [comment] 2022-12-13 22:00
> Is there a way to fix this issue?

@rucanunes Yes, see my reply above.

If your question is: Can you fix it yourself? No, not without forking the library and custom integration and build your own.

**Comment by kovrom** [comment] 2022-12-14 02:53
Same issue. Our Groceries 1.5.0 doesn't work with HA 2022.12.5. Happened previously with v 1.4.1 but was very quickly fixed by @ljmerza. He is a real mvp :)
`Unable to install package ourgroceries==1.5.0: ERROR: Cannot install ourgroceries==1.5.0 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts [notice] A new release of pip available: 22.3 -> 22.3.1 [notice] To update, run: pip install --upgrade pip`
Thank you

**Comment by ljmerza** [comment] 2022-12-14 14:27
that error message is supposed to tell you what package is conflicting. if it doesnt tell; me not sure how to fix it. there's only two packages and they both match the HA version

**Comment by frenck** [comment] 2022-12-14 14:39
@ljmerza They don't and they should not match. They should provide a range, see also my explanation here:

<https://github.com/ljmerza/ha-our-groceries/issues/31#issuecomment-1349066916>

As a general rule of thumb: Don't ever pin exact versions in libraries (unless the library itself has a hard requirement of some sort, which is not the case for this library as hand).

../Frenck

**Comment by ljmerza** [comment] 2022-12-14 14:55
okay should work again on v1.5.1

**Closed by ljmerza** 2022-12-14 14:55 UTC
